name: Worksmi FrontDev - Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: gitleaks-action
        uses: gitleaks/gitleaks-action@v1.6.0

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: Folders
        run: ls

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v12.9.0
        with:
          args: deploy --only hosting:worksmi
        env:
          GCP_SA_KEY: ${{ secrets.GCLOUD_AUTH_DEV }}
          PROJECT_ID: worksmi
          FIREBASE_CLI_EXPERIMENTS: webframeworks