name: Worksmi Backend - Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: gitleaks-action
        uses: gitleaks/gitleaks-action@v1.6.0

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH_DEV }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker to use gcloud command-line tool
        run: |
          gcloud auth configure-docker

      - name: Build and push the container image
        run: |
          docker build -t "gcr.io/worksmi/worksmi-front-dev:${{ github.sha }}" ./
          docker push "gcr.io/worksmi/worksmi-front-dev:${{ github.sha }}"

      - name: Folders
        run: ls

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: worksmi-front-dev
          region: us-central1
          image: gcr.io/worksmi/worksmi-front-dev:${{ github.sha }}



